### ISSUE TITLE
Migrate frontend from CRA to Vite

### ISSUE THREAD

**Issue by chris-t-li** [chingu-voyages/v45-tier3-team-47#25]
Task
* Frontend application is currently built using Create React App which is deprecated by React. 
* Proposed replacement is Vite.js
* Will transfer from CRA to Vite
* Transfer across all app dependencies

**Comment by GIT-Gizmo** [comment]
Hi, is this issue fixed?

**Comment by chris-t-li** [comment]
This issue has been fixed with PR #26

**Comment by GIT-Gizmo** [comment]
Cool
