### ISSUE TITLE
Set up additional backend routes

### ISSUE THREAD

**Issue by parradaniela** [chingu-voyages/v45-tier3-team-47#37]
Mays is working on the routes for Sign in/Sign Up
Backend team members will be pair programming on the remaining backend routes

**Comment by chris-t-li** [comment]
@mtoprak53  Are there any further backend routes to be added? If not, can we close this issue?

**Comment by mtoprak53** [comment]
@chris-t-li I'll check and return to you this evening about this issue.

**Comment by mtoprak53** [comment]
I pushed "edits-on-auth-middleware" branch for Issues #37 & #38. I appreciate any help to link it to these issues and make a PR.

**Comment by mtoprak53** [comment]
Finished with PR #75
