### ISSUE TITLE
Set up authentication

### ISSUE THREAD

**Issue by parradaniela** [chingu-voyages/v45-tier3-team-47#38]
Log in, Log out, Sign up

**Comment by chris-t-li** [comment]
@mtoprak53  Can this issue be closed? I believe this was dealt with PR #46

**Comment by mtoprak53** [comment]
@chris-t-li I'm working on some additions. Trying to finish this evening.

**Comment by mtoprak53** [comment]
I pushed "edits-on-auth-middleware" branch for Issues #37 & #38. I appreciate any help to link it to these issues and make a PR.

**Comment by mtoprak53** [comment]
Completed with PR # 75.
